keymanapp/status.keyman.com

code.js
public/src/app/pull-request/pull-request.component.ts

The pullRequest graph node supports returning the current code review status in the "hovercard" member. It's a bit abstracted rather than what we'd like ideally ("reviewStatus") but it's still possible to pull the value out with a little bit of effort.
Previously, the review status was not correct for PRs that had had changes requested and then those changes approved; we could have got that by scanning all the reviews and building up the aggregate latest status but this is much simpler.

Use hovercard to reduce the pull request review status based on GitHub's algorithm, rather than trying to figure it out ourselves.

---

README.md
code.js
current-sprint.js
github-contributions.js
github-status.js
public/src/app/app.component.css
public/src/app/app.component.html
public/src/app/app.component.ts
public/src/app/app.module.ts
public/src/app/pipes/filter-object-by-date.pipe.ts

This PR adds display of contributions in current sprint cycle to the view. I have set this up to answer my own sprint management questions rather than to necessarily be helpful to outsiders or even other team members. Hence, unless you add the ?c=1 parameter to the URL, you won't see the contribution tables.
I added this to capture information that is no longer as visible given we stopped using Trello.

Show contributions

---

code.js
github-status.js
public/src/app/app.component.css
public/src/app/platforms.ts
public/src/app/pull-request/pull-request.component.css
public/src/app/pull-request/pull-request.component.ts

Draft PRs are shown slightly faded and with a construction barrier.
Status was not always consistently computed but now works from the
list of reviews and should be okay if <100 reviews/comments on a PR.
While I was at it, I tweaked the layout to make more elements fit on
the screen without compromising overall structure.

fix: draft PRs and status now consistent

---

public/src/app/platforms.ts

Long term, we should report on all status checks for the platform.
For now we are only doing the primary test for the platform; this
is sufficient for display.

fix: status checks were not showing

---

public/src/app/sentry/sentry.component.css

With the current white labels, I had a hard time seeing the Sentry error count.
This changes it to orange

change: label.error color from white to orange

---

public/src/app/app.component.css
public/src/app/app.component.html
public/src/app/app.component.ts

Reduce the width of the tier columns with
a download button rather than repeated version,
add all sprint milestones in site view, and
condense the site table so it fits on screen
more easily.

feat: formatting

---

public/src/app/sentry/sentry.component.css

Reverts keymanapp/status.keyman.com#34
I think I will fix the wrapping to resolve the colour issue properly!

Revert "change: label.error color from white to orange"

---

code.js
github-status.js
public/src/app/app.component.html
public/src/app/app.component.ts
public/src/app/pull-request/pull-request.component.ts

Now that we are starting to use GH actions for sites, it is helpful to be reporting on the status of each pull request. This bumps the rate cost for the status query from 35 to 60. Together with the current contributions query cost of 3, we should still be well within 5000/hour (we refresh once per minute = 3780).

feat: status checks for sites

---

code.js
github-status.js
public/src/app/app.component.css
public/src/app/app.component.html
public/src/app/app.component.ts
public/src/app/issue-list/issue-list.component.css
public/src/app/issue-list/issue-list.component.html
public/src/app/pull-request/pull-request.component.css
public/src/app/pull-request/pull-request.component.html
public/src/main.ts

Hovering over a milestone will show the list of issues for that milestone (except for `Future` milestone):
Hovering over a pull request will show details of the PR:
Query cost for GitHub remains 60 (if I add labels to the list of issues, then it goes up to 100+...)

feat: show issue lists

---

code.js
github-issues.js
github-status.js
public/src/app/app.component.html
public/src/app/app.component.ts
public/src/app/issue-list/issue-list.component.css

For performance and complexity reasons, it turns out to be
a lot easier to just read the list of issues from GitHub as
a separate chain of queries. This has an additional cost of
5 points but we will still be well under our threshold (we
may be able to simplify a few other places as well later).
(Not unified yet: unlabeled issues)

feat: read issue details as separate list

---

code.js
public/src/app/app.component.css
public/src/app/app.component.html
public/src/app/app.component.ts
public/src/app/app.module.ts
public/src/app/clipboard/clipboard.component.css
public/src/app/clipboard/clipboard.component.html
public/src/app/clipboard/clipboard.component.spec.ts
public/src/app/clipboard/clipboard.component.ts
public/src/app/issue-list/issue-list.component.html
public/src/app/issue-list/issue-list.component.ts
public/src/app/pull-request/pull-request.component.css
public/src/app/pull-request/pull-request.component.html
public/src/app/utility/escapeHtml.ts
public/src/app/utility/repoShortNameFromGithubUrl.ts

1. fix: use new keyman-version.exe filenames
* When referencing Keyman for Windows 14.0 or later, use new filename format keyman-x.x.x.exe.
2. fix: tweak placement of popups
* Moving cursor onto popups could cause the popups to hide themselves due to a 1px misalignment.
3. feat: add clipboard shortcuts
* Adds clipboard shortcuts for branch names, contribution reports, and issue lists.
Note that the contribution reports and issue lists are currently copied *only* as HTML, which means you can only paste them into places that accept HTML (e.g. Google Docs, Word, but not textarea).

fix: download filenames and feat: clipboard support

---

github-status.js
public/src/app/app.component.ts
public/src/app/platforms.ts
public/src/app/pull-request/pull-request.component.html
public/src/app/pull-request/pull-request.component.ts

Pull Requests don't always show status correctly, for two reasons:
1. GitHub sometimes returns a null status check with a QUEUED state, which the app then saw instead of the correct status check. We see this for the website status checks.
2. We renamed the TC configurations and added versioning into them, which means we need to test only on the parent project name rather than the full status check. This should work into the future as well, when we have new status checks that have the same name pattern.
Also, if any build check fails, this will now be highlighted. The algorithm attempts to find the best corresponding build check for all platforms otherwise, and defaults to the first if no perfect match is found ( which may happen on Common at least).
We still only show one of the status …

fix: Improve Pull Request status reporting

---

public/src/app/app.component.ts

We changed the naming for our milestones from `PddSdd` to `AddSdd` or `BddSdd`. This wasn't accounted for in the milestone sorting, causing `A15S01` to be sorted before `A14S08`. 
This change restores the chronological sorting based on milestone and sprint numbers.

fix: correct milestone sorting

---

public/src/app/pipes/filter-object-by-date.pipe.ts

because string-string became NaN, which sorted randomly somewhat unsurprisingly. Perhaps Nan was grumpy.

fix: flickering contributions

---

public/src/app/app.component.ts
public/src/app/deploy-box/deploy-box.component.ts
server/code.ts
server/data/status-data.ts
server/services/deployment/linux-lsdev-sil-org-alpha.ts
server/services/deployment/linux-lsdev-sil-org-beta.ts
server/services/deployment/linux-lsdev-sil-org-stable.ts
shared/status-source.ts

This change adds the deployment status for Launchpad and llso for beta and alpha builds. It also adds llso to stable builds.

feat: Add Linux deployment status for beta and alpha versions

---

server/services/deployment/launch-pad.ts

This change looks for the publishing date of `keyman-config`. This makes things work if we publish a non-Keyman package to the ppa.

fix: filter for package name on ppa

---

server/services/deployment/linux-lsdev-sil-org.ts
server/services/deployment/packages-sil-org.ts

The source package isn't always listed with a version number on pso and llso. This change uses the `Version` field instead to
retrieve the version number. This gives the version of the binary package - which should be identical to the version of the source
package.

fix: version number extraction on pso and llso

---

public/angular.json
server/code.ts
server/util/httpget.ts

We did not catch failures correctly so if a timed site call resulted in failure, we'd never reset the timer.
Also, enables source maps for angular so we get better errors

fix: handle site failures with catch

---

public/src/app/deploy-box/deploy-box.component.html

Previously we always showed the link to the stable download as link
under the deploy box.

fix: download links

---

public/src/app/app.component.ts
public/src/app/deploy-box/deploy-box.component.ts
server/services/deployment/linux-lsdev-sil-org.ts

The previous fix (#145) missed the fact that if the package name equals the source package name the latter will be omitted. Also
the URL changed.

fix: More adjustments for consolidated Debian package

---

README.md
server/package.json

Without this change building fails because tsc doesn't know `describe` and `it`.

fix: Allow to build server

---

README.md
public/src/app/issue-list/issue-list.component.css
public/src/app/issue-list/issue-list.component.html
public/src/app/pull-request/pull-request.component.css
public/src/app/pull-request/pull-request.component.html
server/keymanapp-test-bot/keymanapp-test-bot-middleware.ts
server/services/github/github-issues.ts
server/services/github/github-status.ts

Shows links between issues and PRs better. But still missing some where GitHub is not reporting the link (e.g. keymanapp/keyman#5700)

fix: linked issues

---

public/src/app/app.module.ts
public/src/app/deploy-box/deploy-box.component.ts
public/src/app/home/home.component.html
public/src/app/issue-list/issue-list.component.ts
public/src/app/popup-coordinator.service.ts
public/src/app/popup/popup.component.ts
public/src/app/pull-request/pull-request.component.ts
public/src/app/sentry/sentry.component.ts

Popups would not pin over data changes as they would be reconstructed. This refactor pulls out the common pinning code into a PopupComponent, and adds a PopupCoordinatorService to track the pin state of popups. This is also groundwork for future consolidation of popup common functionality, css, etc.

fix: persist popups

---

public/src/app/platforms.ts
public/src/app/sentry/sentry.component.html
public/src/app/sentry/sentry.component.ts
public/src/app/sites.ts
public/src/main.ts
server/code.ts
server/services/sentry/sentry-issues.ts

This ended up being a bit of a yak shave. Had to rewrite the sentry issue data service because we can't do cross-project querying on our current sentry.io sponsored plan. In order to avoid hitting rate limits, we have to also delay the 36+ requests by 125msec each.
As our current plan also does not give us webhook notifications for new errors, only for new issues, we now poll the sentry endpoint along with all our other polling.

chore: sentry.io reporting 👮‍♂️

---

server/keymanapp-test-bot/keymanapp-test-bot.ts

This meant that spec links were broken on pull requests.

fix: baseid needs to be issue not pull

---

public/src/app/home/home.component.ts
shared/manual-test/manual-test-parser.ts
shared/manual-test/manual-test-protocols.ts

* retest clause now matches all tests within a protocol or suite
* awaiting test view will show any PR that has incomplete tests, even if other tests have also failed.

fix: bot test match improvements

---

public/src/app/deploy-box/deploy-box.component.ts

Adds simulator links and "All downloads" link. The "Default download from downloads.keyman.com" link is just renamed from "downloads.keyman.com" and is somewhat ... inaccurate for keymanweb.com, perhaps title needs tweaking but it still works.

chore: add simulator links

---

server/keymanapp-test-bot/keymanapp-test-bot.ts

Fixes #186.
Adds a 'has-user-test' label to each PR or issue that has a `# User Testing` section. Removes the label if that section subsequently disappears.
Note that existing PRs and issues will not be affected by this, so we should go ahead and manually search for those and add the label.

feat: add has-user-test label

---

shared/manual-test/manual-test-protocols.ts

This works around what seems to be a GH bug in the id for the pr description anchor changing sporadically. Instead we ref the top of the document.
This is also why I kept trying to fix this and swapping back and forth -- because my test cases were unstable due to this GH issue. (I'm not going
to try and link the PRs in question, but you can find them if you search...)

chore: use base ref for top comment

---

shared/manual-test/manual-test-parser.ts

If tests are part of a suite or group, and all tests in that grouping pass, then the test results will collapse them so that we have less noise.

feat: rollup passed tests

---

public/src/app/issue-list/issue-list.component.css
public/src/app/issue-list/issue-list.component.html
public/src/app/issue-list/issue-list.component.ts
server/services/github/github-issues.ts

This minor tweak only adds the ✔ checkmark to an issue in the issue list if there is a corresponding PR that is marked to close it, and highlights that PR with bold green font. That is not always automatic with GitHub, so don't forget to do that linkage on your PRs/issues to get the benefit:

feat: highlight PRs that close issues

---

public/src/app/deploy-box/deploy-box.component.ts
server/services/deployment/debian.ts

The Keyman 15 packages have been accepted, so we need to adjust the package name. This also means that the `keyman-config` source package is no longer available.

chore: Update Debian package name

---

server/keymanapp-test-bot/artifact-links-comment.ts

Fixes following error, which arises when a build has gone stale.
```
2022-05-21T08:37:25.548740074Z: [ERROR]  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-05-21T08:37:25.549713879Z: [ERROR]  TypeError: Cannot read properties of undefined (reading 'resultingProperties')
2022-05-21T08:37:25.549749479Z: [ERROR]      at Object.<anonymous> (/home/site/wwwroot/server/keymanapp-test-bot/artifact-links-comment.ts:84:42)
2022-05-21T08:37:25.549756079Z: [ERROR]      at Generator.next (<anonymous>)
2022-05-21T08:37:25.549760479Z: [ERROR]      at fulfilled (/home/site/wwwroot/server/dist/server/keymanapp-test-bot/artifact-links-comment.js:5:58)
```

fix: test bot was failing with missing data

---

server/test/manual-test-parser.spec.ts
shared/manual-test/manual-test-parser.ts

fix: support inferred 'all' for test bot retest control

---

public/src/app/count-box/count-box.component.html
public/src/app/count-box/count-box.component.ts
public/src/app/issue-list/issue-list.component.html

If you fixed the last issue for a milestone for a given platform, the issue counter would disappear entirely. This fix makes it so that the issue counter will be visible for the 'all' view, but not for the 'current' view, so that we reduce the noise to active work items for the 'current' view.

fix: show fixed,open issues when view=all

---

public/src/app/pull-request/pull-request.component.ts
shared/artifact-links.ts

@jahorton was looking to update some user tests involving chiral keyboard.
On the CI, **Keyman - Android/ Test: Samples and Test projects** is already creating artifacts for KeyboardHarness, so this adds links for the test-bot

chore: Add Android KeyboardHarness links

---

server/keymanapp-test-bot/emoji-label.ts

If you create an issue that is valid CC format but has no scope, it will
be given 'common' scope by the bot.

fix: use 'common' label for issues without scope

---

server/code.ts

As discourse doesn't notify on changes to tags, we now poll the
community site once a minute so that we get updated tags on the list of
topics.

chore: poll community site

---

shared/users.ts

Revert #397 because of #398 and a related bug #400 that goes infinite
@mr-rogers

fix: Revert #397 of Update users.ts 

---

public/src/app/home/home.component.ts

If a PR comes from a fork:master, then we ended up with a recursive
reference in our tree analysis of the PR chains, which meant that
various views would not see all the open PRs.

fix: recursive ref if fork has PR from master

---

server/keymanapp-test-bot/artifact-links-comment.ts

keymanapp/keyman#10577 upgraded upload-artifact to v4 which caused a change in the name of artifacts. Also we now have a different artifact for each distribution. This change adjust for the name names.
Fixes keymanapp/keyman#10602.

fix: Adjust for changed Linux artifact names

---

server/code.ts
server/data/status-data.ts
server/services/github/github-contributions.ts
server/services/github/github-issues.ts
server/services/github/github-status.ts
server/services/github/github-test-contributions.ts
server/util/github-rate-limit.ts

Fixes #420.
Adds server-side logging for rate limiting and cost for each GraphQL query. Note that this misses rate limit data for the REST API usage (currently only github-milestones.ts, which should have a cost of 1).
Tweaks the expensive github-status:organization query to reduce the cost from 100 to 48, by retrieving fewer PRs per repo (max of 20), and max of 60 repos. This means that if we start getting many PRs on a single repo, we may not have visibility.
This is an interim fix, would be much better to use cached data and fold changes in that are given to us by the GH webhook notifications, but that's a much, much more complex change.

chore: manage rate limits for GitHub

---

public/src/app/pull-request/pull-request.component.ts
server/keymanapp-test-bot/artifact-links-comment.ts
shared/getTeamcityUrlParams.ts

TeamCity appears to be using a new format for its status urls as of a few days ago (version 2024.03?). Updates testbot and status page to parse these new urls (while maintaining support for old pattern for now as well).

fix: new teamcity status url format

---

server/keymanapp-test-bot/emoji-label.ts
shared/issue-labels.ts

Adds 'change', 'style'. This only affects issues; PR labels are managed in keymanapp/keyman repo.

change: tweak issue label list to match current practice

---

server/services/github/github-status.ts

It seems like something changed in the GH backend because all of a sudden our query for labels returned only 'core/', instead of returning labels for all the platforms. So have removed the filter, which means more data coming in...

chore: get git issues going again

---

public/src/app/utility/pullStatus.ts

e.g. for keymanapp/keyman#11637, was matching against the wrong author's review previously, which was not the last review

fix:  use last review date for pr status calculation when comparing against last review request

---

public/src/app/deploy-box/deploy-box.component.ts
server/services/deployment/launch-pad.ts
server/services/deployment/linux-lsdev-sil-org.ts
server/services/deployment/packages-sil-org.ts

- link to `keyman` instead of `keyman-config`
- fix version detection on pso
- use packages for `noble` instead of `focal` to determine version

chore: update links for Linux

---

server/services/deployment/launch-pad.ts

This fixes the problem where we showed the version number from onboard because that was the latest package uploaded to launchpad. We now exactly match the name of the binary package which will report the correct version number for Keyman.

fix: get correct version from Launchpad

---

public/src/app/data/data.model.ts
public/src/app/deploy-box/deploy-box.component.ts
server/code.ts
server/data/status-data.ts
server/services/deployment/npmjs.ts
shared/status-source.ts

npm package @keymanapp/models-types is obsolete, check instead @keymanapp/common-types.

chore: move from @keymanapp/models-types to @keymanapp/common-types

---

server/test/manual-test-parser.spec.ts
shared/manual-test/manual-test-parser.ts

The existing `@keymanapp-test-bot` pattern will continue to be supported, but the commit-trailer style `Test-bot: ` matches other controls we use in commit messages and is recommended for use.
Note that this trailer is only recognized in PR comments at this time; parsing commit messages may be supported in a future update (but with caution because they are less visible in the PR view and workflow, so may cause confusion to testers).
Fixes: keymanapp/keyman#13212

feat: add support for `Test-bot:` trailer in PR comments

---

server/code.ts
server/keymanapp-test-bot/keymanapp-test-bot-middleware.ts

When we updated probot from 12.3.3 to 13.4.5, it looks like its API changed, which I have now located in the release notes at https://github.com/probot/probot/releases/tag/v13.0.0.
This seems to be the new API req.
Fixes: #513

fix: probot api surface change with update

---

server/code.ts
server/package-lock.json
server/package.json
server/services/github/github-status.ts
server/util/httppost.ts

Trying to pinpoint where github-status is falling over after some time running in production. Currently we see a log entry for timing[github] starting but it never returns finishing (this was with a check_suite entry). No errors, just disappears into nowhere.
Test-bot: skip

fix: extra logging and websocket types, and add timeout for http requests

---

public/src/app/data/data.model.ts
public/src/app/service-state-popup/service-state-popup.component.html
public/src/app/service-state-popup/service-state-popup.component.ts
server/data/status-data.ts
shared/services.ts

This allows us to see how long services have been down for, or attempting to read from service etc. Service timers start showing after 5 seconds for loading state (and update each second), or 3 minutes for successful (loaded) state (and update each minute). For error or unknown states, the timer shows immediately and updates every second.
Note that this does not show when the last actual change was, because this reflects only the loading state -- so each load attempt will reset the corresponding counter. We may refresh this later for more detail.
Test-bot: skip

change: show counters on service state

---

server/keymanapp-test-bot/artifact-links-comment.ts

Not clear when this changed, but it seems the GH API response now uses target_url for TC links
Test-bot: skip

fix: use target_url instead of url

---

server/keymanapp-test-bot/artifact-links-comment.ts

Note: GH API has always used target_url, my bad. I was transforming on my end
Test-bot: skip

chore: update target_url once more

---

public/src/app/data/data.model.ts
public/src/app/home/home.component.html
public/src/app/home/home.component.ts

This fixes performance and also the link to each user's view.
Test-bot: skip

fix: calculate user order for contributions at data load
