keymanapp/status.keyman.com

code.js, public/src/app/app.component.ts
Teamcity seems to report 'running' status as 'success' even when not complete, and we have to retrieve the status for running builds separately. Still, seems to work okay!
=> Update tier build status for stable and support pending status

public/src/app/app.component.html, public/src/app/app.component.ts
Somewhat ugly but now shows multiple milestones in open issue view; also fixes milestone:Other to no:milestone
=> Support multiple milestones

public/src/app/app.component.css, public/src/app/app.component.html, public/src/app/app.component.ts
Added bonus: improves the display of the date headers in the contributions table.
=> The Great Big Avatar Fix

public/src/app/app.component.css, public/src/app/app.component.html, public/src/app/pull-request/pull-request.component.css, public/src/app/pull-request/pull-request.component.html, public/src/styles.css
=> The Great Big Avatar Fix Again

package.json, public/src/app/app.component.css, public/src/app/app.component.html, public/src/app/app.component.ts
Small rider gives support for clicking avatar to lock drop down open.
Also automatically load localenv.sh -- this requires bash as shell for npm:
https://stackoverflow.com/a/46006249/1836776
=> fix: wrong dates in contributions

README.md, public/src/app/pull-request/pull-request.component.css, public/src/assets/LICENSE_OFL.txt, public/src/styles.css
This is a little frivolous but I was checking that all my dev processes and sites are working on my alternate machine and this was a simple tweak to test that.
=> fix: emoji font for status

github-status.js, public/src/app/app.component.css, public/src/app/app.component.html, public/src/app/app.module.ts, public/src/app/count-box/count-box.component.css, public/src/app/count-box/count-box.component.html, public/src/app/count-box/count-box.component.spec.ts, public/src/app/count-box/count-box.component.ts
Also, refactor issue count boxes and related tidy up.
=> feat: show keyboards and lexical models

README.md, code.js, current-sprint.js, github-contributions.js, github-status.js, package-lock.json, package.json, public/src/app/app.component.html, public/src/app/app.component.ts, public/src/app/status/status.service.ts
This allows you to add a `?sprint=P8S4` parameter to view sprint data for P8S4. The only information that is really relevant for earlier sprints is the contributions data. It's not all that beautiful, but I think it all works.
=> feat: hidden feature -- earlier sprints

github-status.js, public/src/app/app.component.css, public/src/app/app.component.html, public/src/app/app.module.ts, public/src/app/issue-list/issue-list.component.css, public/src/app/issue-list/issue-list.component.html, public/src/app/issue-list/issue-list.component.spec.ts, public/src/app/issue-list/issue-list.component.ts
Corrects the issue count at top to be uncategorized rather
than without milestone, and adds a popup of the issues.
=> feat: issues without milestone

github-status.js, public/src/app/app.component.html, public/src/app/app.component.ts, public/src/app/platforms.ts
That's a thorny one to solve (pagination etc) but I was missing issues on Developer so decided to at least remind myself of the problem (while waiting for iOS builds...)
=> fix: too many issues for Developer so counts are inaccurate

README.md, _start_server.bat, _start_server.sh, github-status.js, package-lock.json, package.json, public/src/app/app.component.css, public/src/app/app.component.html, public/src/app/app.component.ts
At the same time, add a total issue count for each platform.
=> fix: handle new label names

code.js, public/src/app/app.component.html, public/src/app/app.component.ts, public/src/app/platforms.ts
When we moved to beta and the new build configuration setup,
some of the status data sources needed to be updated.
Also added a beta-test column to the view.
=> chore: update for beta

code.js, github-issues.js, github-status.js, public/src/app/app.component.css, public/src/app/issue-list/issue-list.component.css, public/src/app/issue-list/issue-list.component.html, public/src/app/issue-list/issue-list.component.ts, public/src/app/pull-request/pull-request.component.css, public/src/app/pull-request/pull-request.component.html, public/src/app/pull-request/pull-request.component.ts, public/src/app/utility/labelColor.ts
Also had some thoughts about a web-worker-based background refresh
to reduce query load but that will come in a future update.
=> feat: add related issues and PR labels

public/src/app/issue-list/issue-list.component.html, public/src/app/issue-list/issue-list.component.ts
Shows a check mark to the left of the issue. Also adds linked PRs in the clipboard copy of the issue list.
=> feat: highlight issues that have associated PRs

public/package.json, public/src/environments/environment.ts
=> chore: production builds

public/src/app/app.component.html, public/src/app/issue-list/issue-list.component.css, public/src/app/issue-list/issue-list.component.html, public/src/app/issue-list/issue-list.component.ts, public/src/app/pull-request/pull-request.component.html, public/src/app/pull-request/pull-request.component.ts, public/src/app/sentry/sentry.component.html, public/src/app/sentry/sentry.component.ts, public/src/styles.css
Starts keeping popups from going off the edge of the screen in a lazy way.
Only does issue-list right now, others to come.
=> fix: horz gravity for issue list popups

server/code.ts
=> fix: current sprint data

server/code.ts, server/identity/slack.ts, server/services/deployment/itunes.ts, server/services/slack/slack.ts, server/test/README.md, server/test/slack.ts
Initial integration with Slack.
=> feat: slack-lgtm

public/src/app/app.component.css, public/src/app/deploy-box/deploy-box.component.css, public/src/app/issue-list/issue-list.component.css, public/src/app/pull-request/pull-request.component.css, public/src/app/sentry/sentry.component.css
Fixes #130.
Delays display of popups by 0.25s and then fades them in which helps when moving the mouse across the screen to stop chaotic popups everywhere...
=> feat: fade in

public/package-lock.json, public/package.json, public/src/app/issue-list/issue-list.component.html, public/src/app/pull-request/pull-request.component.css, public/src/app/pull-request/pull-request.component.html, public/src/app/pull-request/pull-request.component.ts, public/tsconfig.json
* shows +/- change counts in PRs
* fixes link for 'Other' issues in websites
* adds emoji scanning for title to allow grouping in PR series
=> feat: show change counts in PRs

public/src/app/app.component.css, public/src/app/app.component.html, public/src/app/app.component.ts, public/src/app/sentry/sentry.component.css, public/src/app/sentry/sentry.component.html, public/src/app/sentry/sentry.component.ts, server/code.ts, server/services/github/github-status.ts, server/services/sentry/sentry-issues.ts
=> feat: split crash reports by tier

public/src/app/app.component.html, public/src/app/app.component.ts
Action arising from spacebarText post mortem.
=> feat: show test runs for stable tier

public/src/app/home/home.component.ts, public/src/app/pull-request/pull-request.component.css, public/src/app/pull-request/pull-request.component.html, public/src/app/pull-request/pull-request.component.ts, server/keymanapp-test-bot/keymanapp-test-bot.ts
Also, tweak test result to include 'pending' state.
=> feat: add user testing status to status.keyman.com

public/src/app/home/home.component.ts, public/src/app/pull-request/pull-request.component.css, public/src/app/pull-request/pull-request.component.html, public/src/app/pull-request/pull-request.component.ts
Cleans up status reporting for pull requests, fixes one bug on user testing status bleeding through into build status.
Adds a pin for pull request popups
=> fix: pull request status

public/src/app/home/home.component.ts, public/src/app/issue-list/issue-list.component.html, public/src/app/issue-list/issue-list.component.ts
Fixes #157.
Also removes check mark from issues that only have linked issues, not PRs.
=> fix: duplicate timeline items

public/src/app/home/home.component.css, public/src/app/home/home.component.html, public/src/app/home/home.component.ts, public/src/app/pull-request/pull-request.component.css, public/src/app/pull-request/pull-request.component.ts, public/src/app/utility/pullStatus.ts
Three new views into pull requests (mostly because I was struggling to keep up with PR volume!)
PRs may be shown in multiple categories (except if in Draft or Ready to Merge).
PRs only shown once.
PRs only shown once.
=> feat: pull request views

public/package-lock.json, public/package.json, public/src/app/home/home.component.ts, public/src/app/pull-request/pull-request.component.ts, server/keymanapp-test-bot/artifact-links-comment.ts, server/keymanapp-test-bot/keymanapp-test-bot.ts, server/keymanapp-test-bot/test-artifact-links.ts
* Fixes version information not always correct for artifact links
* Fixes some emoji unrecognised
* Updates various npm packages
=> fix: version info in artifact links and emoji and security patches

server/keymanapp-test-bot/keymanapp-test-bot.ts
Keymanapp-test-bot was failing on issues due to logging
=> fix: bot log error

server/keymanapp-test-bot/keymanapp-test-bot.ts, shared/manual-test/manual-test-parser.ts, shared/manual-test/manual-test-protocols.ts
For building an comment link, it should be the issue id, not the pr id
=> fix: bot base issue id was wrong

package-lock.json, public/src/app/deploy-box/deploy-box.component.ts, public/src/app/home/home.component.ts, server/code.ts, server/data/status-data.ts, server/services/deployment/itunes.ts, server/services/deployment/play-store.ts, shared/status-source.ts
Fixes #111.
Testflight links not required as they handled together with iOS store links?
=> chore: add FirstVoices store links

public/src/app/utility/pullStatus.ts
=> fix: check only GitHub Actions for status

public/src/app/home/home.component.css, public/src/app/home/home.component.html, public/src/app/home/home.component.ts, public/src/app/status/status.service.ts, public/src/environments/environment.prod.ts, public/src/environments/environment.ts, server/code.ts
Adds a button that forces a server-side data refresh, useful in cases where there has been a network glitch or webhook timeout.
=> feat: add refresh button

public/src/app/clipboard/clipboard.component.html, public/src/app/clipboard/clipboard.component.ts, public/src/app/home/home.component.css
=> feat: spinner for copy-to-clipboard

shared/manual-test/manual-test-protocols.ts
=> fix: handle undefined names in protocols

public/src/app/home/home.component.html, public/src/app/home/home.component.ts, server/data/status-data.ts, server/services/github/github-test-contributions.ts
Fixes #153.
This one is for @MakaraSok!
=> feat: report on test contributions

server/data/status-data.ts, server/keymanapp-test-bot/artifact-links-comment.ts, server/util/httpget.ts, server/util/httppost.ts
This doesn't cover all the async/await or promise chains but should deal with the majority. Fixes a number of sentry error reports.
=> fix: handle network errors

public/src/app/agent-detail/agent-detail.component.css, public/src/app/agent-detail/agent-detail.component.html, public/src/app/agent-detail/agent-detail.component.spec.ts, public/src/app/agent-detail/agent-detail.component.ts, public/src/app/app.module.ts, public/src/app/build-queue/build-queue.component.css, public/src/app/build-queue/build-queue.component.html, public/src/app/build-queue/build-queue.component.spec.ts, public/src/app/build-queue/build-queue.component.ts, public/src/app/home/home.component.css, public/src/app/home/home.component.html, public/src/app/home/home.component.ts, server/services/teamcity/teamcity.test.ts, shared/platforms.ts
One of the missing components for this site -- a quick view into build agent status and build queue. Updates once per minute.
=> feat: build agent and queue component views

shared/artifact-links.ts
Update artifact comment links for Developer artifacts coming from new
Developer build configuration.
=> chore: developer artifacts

public/src/app/home/home.component.css, public/src/app/home/home.component.html
=> feat: add [+] button to create issue for scope/site

public/src/app/app.module.ts, public/src/app/home/home.component.html, public/src/app/home/home.component.ts, public/src/app/issue/issue.component.css, public/src/app/issue/issue.component.html, public/src/app/issue/issue.component.spec.ts, public/src/app/issue/issue.component.ts, public/src/app/pipes/filter-issue-by-label.pipe.ts, server/keymanapp-test-bot/keymanapp-test-bot.ts
=> feat: add user test issues to status view

public/src/app/build-queue/build-queue.component.ts, shared/platforms.ts
=> chore: tweak build config names

public/src/app/home/home.component.ts
Inspired by https://stackoverflow.com/a/8245055/1836776
=> feat: sort pulls by branch ref

public/src/app/deploy-box/deploy-box.component.html, public/src/app/deploy-box/deploy-box.component.ts
Fixes #250. Well, works around it.
=> fix: disable linux.lsdev.sil.org link as it does not work

public/src/app/app.module.ts, public/src/app/box-pr-author/box-pr-author.component.html, public/src/app/box-pr-author/box-pr-author.component.spec.ts, public/src/app/box-pr-author/box-pr-author.component.ts, public/src/app/box-pr-base/box-pr-base.component.css, public/src/app/box-pr-base/box-pr-base.component.html, public/src/app/box-pr-base/box-pr-base.component.spec.ts, public/src/app/box-pr-base/box-pr-base.component.ts, public/src/app/box-pr-platform/box-pr-platform.component.css, public/src/app/box-pr-platform/box-pr-platform.component.html, public/src/app/box-pr-platform/box-pr-platform.component.spec.ts, public/src/app/box-pr-platform/box-pr-platform.component.ts, public/src/app/box-pr-project/box-pr-project.component.html, public/src/app/box-pr-project/box-pr-project.component.spec.ts, public/src/app/box-pr-project/box-pr-project.component.ts, public/src/app/box-pr-status/box-pr-status.component.html, public/src/app/box-pr-status/box-pr-status.component.spec.ts, public/src/app/box-pr-status/box-pr-status.component.ts, public/src/app/home/home.component.css, public/src/app/home/home.component.html, public/src/app/home/home.component.ts, public/src/app/pull-request/pull-request.component.css, public/src/app/pull-request/pull-request.component.html, public/src/app/pull-request/pull-request.component.ts
=> feat: ultimate base branch

public/src/app/home/home.component.html, public/src/app/home/home.component.ts, server/code.ts, server/data/status-data.ts, server/services/discourse/discourse.ts, shared/status-source.ts, shared/users.ts
=> feat: community site post contributions

shared/platforms.ts
=> chore: Developer beta build configuration change

public/src/app/home/home.component.html, public/src/app/home/home.component.ts, public/src/app/issue-list/issue-list.component.ts, public/src/app/utility/issue-clipboard.ts
Copies list of all issues for current sprint onto the clipboard.
=> feat: issue mega clipboard

public/src/app/home/home.component.html, public/src/app/home/home.component.ts
=> feat: copy PRs to clipboard

public/src/app/issue-list/issue-list.component.ts
=> fix: copy issue list returns object

public/src/app/contributions/contributions.component.ts
=> fix: limit post contributions to current sprint

public/src/app/pull-request/pull-request.component.ts, server/keymanapp-test-bot/artifact-links-comment.ts
That's probably not quite right yet...
=> chore(linux): Add packaging GHA artifacts

server/keymanapp-test-bot/artifact-links-comment.ts, shared/artifact-links.ts
=> chore: GHA artifact link tweaks

public/src/app/sites.ts, server/services/sentry/sentry-issues.ts
=> chore: Remove donate.keyman.com from status site

public/src/app/deploy-box/deploy-box.component.ts, public/src/app/home/home.component.ts, server/code.ts, server/data/status-data.ts, server/services/deployment/npmjs.ts, shared/status-source.ts
Replaces @keymanapp/lexical-model-compiler
=> feat: add npm package @keymanapp/kmc

public/src/app/app.module.ts, public/src/app/community-queue/community-queue.component.css, public/src/app/community-queue/community-queue.component.html, public/src/app/community-queue/community-queue.component.spec.ts, public/src/app/community-queue/community-queue.component.ts, public/src/app/count-box/count-box.component.html, public/src/app/count-box/count-box.component.ts, public/src/app/home/home.component.html, public/src/app/home/home.component.ts, public/src/app/sites.ts, public/src/app/status/status.interface.ts, server/code.ts, server/data/status-data.ts, server/services/discourse/discourse.ts
=> feat: display community site topic queue

server/keymanapp-test-bot/emoji-label.ts, server/keymanapp-test-bot/keymanapp-test-bot.ts, server/keymanapp-test-bot/pull-request-milestone.ts
* Where possible, apply epic labels and emojis automatically.
* Automatically assign unmilestoned PRs to current sprint.
=> feat: automatic epic labels, milestones and emojis

server/keymanapp-test-bot/emoji-label.ts
=> chore: fix top ref

server/keymanapp-test-bot/issue-milestone.ts, server/keymanapp-test-bot/keymanapp-test-bot.ts
=> feat: apply milestone when closing issue

server/keymanapp-test-bot/emoji-label.ts
Fixes #381.
For issues with titles that match our Conventional Commits pattern, we can apply corresponding labels automatically. Ignores issues with non- matching titles.
=> feat: apply labels according to issue title

server/keymanapp-test-bot/artifact-links-comment.ts
=> chore: show build status in test artifacts

server/services/discourse/discourse.ts
=> fix: limited Discourse contribution count

public/src/app/assigned-issues/assigned-issues.component.html
=> feat: assigned issues link

server/code.ts, server/services/github/github-status.ts
=> chore: logging

public/src/state.ts
=> fix: unassigned issues unclick returns home

public/src/app/utility/pullStatus.ts, server/services/github/github-status.ts
=> feat: track requests for re-review

shared/users.ts
This adds @dinakaranr who is succeeding @bharanidharanj for user testing.
=> chore: Add dinakaranr

server/services/sentry/sentry-issues.ts
=> feat: exclude low-priority Sentry errors

public/src/app/box-pr-author/box-pr-author.component.html, public/src/app/data/data.model.ts
epics now listed as authorless
=> feat: split epics from author

public/src/app/count-box/count-box.component.html
=> fix: show zero-unfixed issue boxes

public/src/app/contributions-tab/contributions-tab.component.ts, public/src/app/contributions/contributions.component.css, public/src/app/contributions/contributions.component.html, public/src/app/contributions/contributions.component.ts
=> feat: make time-zone based availability more visible

shared/users.ts
=> chore: rename nyny's community username

shared/issue-labels.ts
See-also: keymanapp/keyman#13780
=> chore: add 'maint' type

public/src/app/home/home.component.css, public/src/app/overview-tab/overview-tab.component.css, public/src/app/overview-tab/overview-tab.component.html, server/keymanapp-test-bot/emoji-label.ts, server/services/github/code-owners.ts, server/test/CODEOWNERS, shared/users.ts
=> maint: remove platform advocates and parse commented CODEOWNERS

server/code.ts, server/package-lock.json, server/package.json
=> chore: move to express v5

server/keymanapp-test-bot/emoji-label.ts
=> maint: set issue type automatically based on issue title

server/services/sentry/sentry-issues.ts
=> feat: improve sentry rate limiting

server/services/sentry/sentry-issues.ts
=> fix: make sentry return array map correct structure

public/src/app/data/data.model.ts
=> fix: break contributions down into days by current timezone

server/keymanapp-test-bot/artifact-links-comment.ts
=> chore: add logging for testbot
